name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.AIML_COMMON_CICD_TOKEN }}

    # # Install dependencies
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}
    # - name: Install dependencies
    #   run: |
    #     $CONDA/bin/conda env update --file environment.yml --name ai-course
        
    # Build the book
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: "data-mining-course"
        
    - name: Build the book
      shell: bash -l {0}
      run: |
        jupyter-book build data_science

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: data_science/_build/html
#         name: deploy

# on:
#   # Trigger the workflow on push to main branch
#   push:
#     branches:
#       - main

# # This job installs dependencies, build the book, and pushes it to `gh-pages`
# jobs:
#   build-and-deploy-book:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest]
#         python-version: [3.8]
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         submodules: recursive
#         token: ${{ secrets.AIML_COMMON_CICD_TOKEN }}

#     # Install dependencies
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v1
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install dependencies
#       run: |
#         pip install -r requirements.txt

#     # Build the book
#     - name: Build the book
#       run: |
#         jupyter-book build data_mining

#     # Deploy the book's HTML to gh-pages branch
#     - name: GitHub Pages action
#       uses: peaceiris/actions-gh-pages@v3.6.1
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: data_mining/_build/html

# name: deploy

# on:
#   # Trigger the workflow on push to main branch
#   push:
#     branches:
#       - main

# # This job installs dependencies, build the book, and pushes it to `gh-pages`
# jobs:
#   build-and-deploy-book:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest]
#         python-version: [3.8]
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         submodules: recursive
#         token: ${{ secrets.AIML_COMMON_CICD_TOKEN }}

#     # Install dependencies
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v1
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install dependencies
#       run: |
#         pip install -r requirements.txt

#     # Build the book
#     - name: Build the book
#       run: |
#         jupyter-book build data_science

#     # Deploy the book's HTML to gh-pages branch
#     - name: GitHub Pages action
#       uses: peaceiris/actions-gh-pages@v3.6.1
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: data_science/_build/html